### ISSUE TITLE
Move project to WebdriverIO Community Org

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-rerun-service#17]
Hey @mikesalvia  ,

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem!

I was wondering if you would be interested moving this repository into the [WebdriverIO Community](https://github.com/webdriverio-community) organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by mikesalvia** [comment]
@christian-bromann This is a day is something I kind of hoped for as an engineer, and it is here. I have to say would not be possible without the fellow members of the JW Player Test Engineering organization (at the time of the release namely, @esaari & @aizaztoppa) as well as several contractors which make up our team. We have been really excited about the contributions as well as the depth in which we can apply Webdriver.IO to our functional test strategy.

The quick answer is yes, please, (insert taken my money meme here), however, this project was created during a Hackweek @ JW Player, therefore, in some ways, it isn't my full choice to move it.

That being said, I will today put into motion this request, which considering JW Player's dedication to open-source, I don't think will have much resistance.

I want to thank you for being supportive of the community at large and continually improving the Webdriver.IO framework!

**Comment by mikesalvia** [comment]
And in my nervousness, I accidentally closed this, re-opened, standby for migration confirmation.

**Comment by mikesalvia** [comment]
@christian-bromann I got partial permission we just would need to preserve the current MIT license of the project, is that OK? I wasn't sure what the policy and protocol are from your side.

**Comment by christian-bromann** [comment]
> is that OK?

Oh yeah, super ok. I am not planning to change much and I still would love if your team keeps maintaining the package. Moving them into a community org helps the project to better autogenerate documentation, ensure that bug fixes can be made and released without waiting for a single person to free up some time for open source work etc. It also will allow us core maintainer to better support when it comes to breaking changes and major version updates. You see this approach in other bigger OSS projects as well.

Here are the steps that are necessary to do this transition:

1. move this repository into the `webdriverio-community` organisation, see more information on that in the [GitHub docs](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)
2. then add [`wdio-user`](https://www.npmjs.com/~wdio-user) to the list of maintainer of the project on NPM

That should be it. Let me know if you have any questions. Thank you!

**Comment by mikesalvia** [comment]
@christian-bromann I have a draft of a Medium article if you want to take a look at it. https://medium.com/jw-player-engineering/wdio-re-run-service-finds-a-new-home-in-the-webdriver-io-community-organization-cbc9136f95e9

**Comment by mikesalvia** [comment]
Project migration has begun, will publish the Medium article later today.

**Comment by mikesalvia** [comment]
![Screen Shot 2021-05-21 at 2 03 15 PM](https://user-images.githubusercontent.com/6209204/119179754-519dce80-ba3d-11eb-9a42-674ffe8d6cf8.png)

**Comment by mikesalvia** [comment]
@christian-bromann Hit a roadblock.

**Comment by christian-bromann** [comment]
@mikesalvia please add `wdio-user` as NPM maintainer __not__ GitHub user

**Comment by mikesalvia** [comment]
Ahhh, perfect. The Medium article is live.

**Comment by mikesalvia** [comment]
@christian-bromann User has been added as NPM maintainer! :-) Closing this...

Happy to be here! :-)

**Comment by christian-bromann** [comment]
Awesome, welcome Mike!
