### ISSUE TITLE
Re-run fails when using Cucumber

### ISSUE THREAD

**Issue by itayTipalti** [webdriverio-community/wdio-rerun-service#19]
When using cucumber framework, in a scenario of a failure in one of the steps, the rerun is not performed and I get an error regarding missing suite name:
![image](https://user-images.githubusercontent.com/83645807/123069203-3e569800-d41b-11eb-931f-4ee2148a1ee4.png)
![image](https://user-images.githubusercontent.com/83645807/123069226-444c7900-d41b-11eb-8e03-ac69f05bb7c5.png)
![image](https://user-images.githubusercontent.com/83645807/123069259-4a425a00-d41b-11eb-9396-42c466a5ee34.png)

**Comment by christian-bromann** [comment]
@itayTipalti thanks for reporting. Can you provide a reproducible example?

Any contributions are appreciated.

**Comment by itayTipalti** [comment]
@christian-bromann 
I used the project which is generated using the npx tool. then I added the rerun service to the wdio.conf.js and after it I just added (like in the picture) a failure on purpose to activate the retry. I got an error doing so.

**Comment by itayTipalti** [comment]
@christian-bromann 
it doesn't work only in wdio7

**Comment by mikesalvia** [comment]
There is a V6 version 1.6.x and a V7 version 1.7.2 (is latest)

**Comment by mikesalvia** [comment]
@itayTipalti Can we close this?

**Comment by itayTipalti** [comment]
yes, thanks @mikesalvia
