### ISSUE TITLE
Rerun-service status map does not match with result

### ISSUE THREAD

**Issue by yopasa94** [webdriverio-community/wdio-rerun-service#27]
status map does not match with scenario result status, it produces an 'unknown' which writes rerun json files for all scenarios and appends them into the rerun script even if the scenarios have passed

![image](https://user-images.githubusercontent.com/22714699/145443020-33e71c17-0690-4613-aa1d-6a60d663c557.png)

Cucumber message enum contains UPPER CASE properties
![image](https://user-images.githubusercontent.com/22714699/145446751-46684178-565f-4f9e-90e5-26bef8a9b648.png)

**Comment by mikesalvia** [comment]
Fixed in #31 will be included in 1.7.3.
