### ISSUE TITLE
Rerun service is not working with selenium-standalone & cucumber gherkin

### ISSUE THREAD

**Issue by munishusa** [webdriverio-community/wdio-rerun-service#28]
Hello,

I followed the instruction as mentioned in https://webdriver.io/docs/wdio-rerun-service

But still rerun is not working for me.  Below are the changes I made to package.json and wdio.config.ts file.  

 
----------------------------------------- package.json ---------------------------------------------------
"wdio-rerun-service": "^1.7.2",

![image](https://user-images.githubusercontent.com/71284708/146846734-438da941-42a3-4c2c-872b-a9a7d6de0d42.png)

---------------------------------------- wdio.config**.ts** ----------------------------------------------
const RerunService = require('wdio-rerun-service');
..
..
..
services: [
    [
      'selenium-standalone',
      {
        drivers: { chrome: true, chromiumedge: 'latest' },
        logs: 'logs',
      },
    ],
    [
      RerunService,
      {
        rerunDataDir: './e2e/custom-rerun-directory',
        rerunScriptPath: './e2e/custom-rerun-directory/custom-path-for-rerun.sh',
      },
    ],
  ],

![image](https://user-images.githubusercontent.com/71284708/146847161-262deccf-aa16-45ac-9281-e4a38247c605.png)

==============================================================

I dont know what I am missing.   Do I need to add any code in hook.

**Comment by munishusa** [comment]
Error Screen.
![image](https://user-images.githubusercontent.com/71284708/147009042-a9fd53a1-85a6-49c6-82a6-84501a77d075.png)

**Comment by stephenrafferty3** [comment]
Seeing the exact same thing, is there an update on this?

**Comment by mikesalvia** [comment]
@stephenrafferty3 @munishusa Hey guys, sorry about delay, I am looking into this. It looks like there maybe an issue with parsing the failing featues.

The offending code is here:
```
const failureLocationsUnique = [...new Set(failureLocations)];
failureLocationsUnique.forEach(failureLocation => {
  rerunCommand += ` --spec=${failureLocation}`;
});
```

Do you guys know how to monkey patch your `node_modeules`? Could you `console.log` the values of `failureLocations` and `failureLocationsUnique`?

**Comment by mikesalvia** [comment]
Will look at this beginning of next week.

**Comment by mikesalvia** [comment]
@stephenrafferty3 @munishusa Sorry for the delay. As referenced in #34 there is incompatibility with the newer `@wdio/cucumber-framework` which returns the result differently, revert that to `7.3.1` and we will be looking at how to support the newer versions.

**Comment by mikesalvia** [comment]
This should now be fixed!
