### ISSUE TITLE
The Passed Scenarios was added into rerun.sh

### ISSUE THREAD

**Issue by nghhung** [webdriverio-community/wdio-rerun-service#29]
This is my package.json:

`"wdio-rerun-service": "^1.7.2"`

This is the rerun JSON data
File 1:
`[{"location":"/Users/hungnguyen/geo-locations-web/e2e/e2e/src/features/Acciona/Login.feature:3","failure":"Error: \u001b[2mexpect(\u001b[22m\u001b[31mreceived\u001b[39m\u001b[2m).\u001b[22mtoEqual\u001b[2m(\u001b[22m\u001b[32mexpected\u001b[39m\u001b[2m) // deep equality\u001b[22m\n\nExpected: \u001b[32m\"ACCIONA - LinkedSite\"\u001b[39m\nReceived: \u001b[31m\"Signin\"\u001b[39m\n    at World._default (/Users/hungnguyen/geo-locations-web/e2e/e2e/src/support/check/checkTitle.js:17:19)"}]`
File 2:
`[{"location":"/Users/hungnguyen/geo-locations-web/e2e/e2e/src/features/Acciona/SortResrouce.feature:6"}]`

This is rerun.sh file:
`DISABLE_RERUN=true node_modules/.bin/wdio e2e/config/wdio.conf.js  --spec=/Users/hungnguyen/geo-locations-web/e2e/e2e/src/features/Acciona/Login.feature:3 --spec=/Users/hungnguyen/geo-locations-web/e2e/e2e/src/features/Acciona/SortResrouce.feature:6`

I see it add all files regardless of pass or fail into rerun.sh

**Comment by mikesalvia** [comment]
Can you post your console? Like how do the test look at end of testing? I can look at this beginning of next week.

**Comment by mikesalvia** [comment]
Fixed in #31 will be included in 1.7.3.
