### ISSUE TITLE
rerun script is invalid on Windows

### ISSUE THREAD

**Issue by algoritmus** [webdriverio-community/wdio-rerun-service#30]
wdio: 7.0.7
rerun: 1.7.2

Hello,

The generated rerun.bat file is not a valid command for Windows ( at least on my machine)

DISABLE_RERUN=true node_modules/.bin/wdio run --spec=C:/Apps/test/features/01_test.feature:5

DISABLE_RERUN=true. this is not recognised

should be set DISABLE_RERUN= true if it is an env variable

Working line would be:

set DISABLE_RERUN=true && npx wide run ./wdio.conf.ts --spec=C:/Apps/test/features/01_test.feature:5

Do I miss something ?

Thanks

Attila

**Comment by munishusa** [comment]
> wdio: 7.0.7 rerun: 1.7.2
> 
> Hello,
> 
> The generated rerun.bat file is not a valid command for Windows ( at least on my machine)
> 
> DISABLE_RERUN=true node_modules/.bin/wdio run --spec=C:/Apps/test/features/01_test.feature:5
> 
> DISABLE_RERUN=true. this is not recognised
> 
> should be set DISABLE_RERUN= true if it is an env variable
> 
> Working line would be:
> 
> set DISABLE_RERUN=true && npx wide run ./wdio.conf.ts --spec=C:/Apps/test/features/01_test.feature:5
> 
> Do I miss something ?
> 
> Thanks
> 
> Attila

Did re-run worked for you in windows machine with your suggested changes ?  If Yes, Please share the code where you made the changes.  It will be a HUGE help.  Thanks

**Comment by SCG82** [comment]
https://github.com/SCG82/wdio-rerun-service/pull/2 (I will change the target branch once https://github.com/webdriverio-community/wdio-rerun-service/pull/42 and https://github.com/SCG82/wdio-rerun-service/pull/1 are merged in)
