### ISSUE TITLE
Feature: Add possibility to add flags/parameters to wdio rerun command.

### ISSUE THREAD

**Issue by lamkovod** [webdriverio-community/wdio-rerun-service#37]
Some users launching wdio with custom flags or parameters. 
ReRunService should be able to handle this. It could be done with additional property.
Example:
```
        [
            RerunService,
            {
                customParameters: ['--firefox'],
            },
        ],
```
Generated `.sh`:
`DISABLE_RERUN=true node_modules/.bin/wdio ./config/wdio.conf.js --firefox  --spec=test/features/login/login-errors.feature:14`

**Comment by esaari** [comment]
Addressed by https://github.com/webdriverio-community/wdio-rerun-service/pull/38
