### ISSUE TITLE
wdio-rerun-service

### ISSUE THREAD

**Issue by gunsingh-clgx** [webdriverio-community/wdio-rerun-service#50]
Hi Team , 

We are working on the **"wdio-rerun-service"** , I am executing multiple feature (for e.g.   **A.feature, B.feature, C.feature**)files for my **e2e cucumber** test cases and once execution is completed, I should have multiple "json" files generated(for e.g. **rerunA.json, rerunB.json, rerunC.json** ) with each ".json" file tells me about the number of failures on each ".feature" file.

And since, these ".json" files are getting generated on the basis of current date and time, we have this behaviour when workers for test is being created at the same time then rerun.json files get generated with the same name and next failures gets overwritten with the old failures. 

Because of this we are unable to get the list of all failures and eventually unable to rerun the all failed scenarios again.

[https://github.com/webdriverio-community/wdio-rerun-service/blob/eca59de23dc1304d57c5041f44e6320f65011055/src/index.ts#L68](url)

and we also tried to change the code to some random **UUID generation**, and it worked so you can also take a look this way to fix or advise us the workaround.

**Comment by SCG82** [comment]
@gunsingh-clgx Did v2.0.2 (or 2.0.1) solve this issue?

**Comment by gunsingh-clgx** [comment]
Hi Team , after changing it to the latest version , my rerun.json or rerun.sh files are not getting generated .
shall I also have to make the changes somewhere else as well ?

**Comment by gunsingh-clgx** [comment]
Hi Team , Any updates on my issue

**Comment by SCG82** [comment]
@gunsingh-clgx What is the latest working version of this service for you?

**Comment by gunsingh-clgx** [comment]
v2.0.2
