### ISSUE TITLE
How to execute the re-run shell script after its been generated.

### ISSUE THREAD

**Issue by suleytron** [webdriverio-community/wdio-rerun-service#59]
Hi,
I have followed the documentation available here: https://v7.webdriver.io/docs/wdio-rerun-service/#re-run-vs-retry
I am getting the expected output of a json file and a Shell script. So far so good.
`              [RerunService, {
                rerunDataDir: 'output/wdio-rerun-service',
                rerunScriptPath: 'output/wdio-rerun-script.sh',
                ignoredTags: ['@wip', '@web'],
            }],`

The piece I am having trouble with is how to incorporate this into my run command/ package.json?

I tried this kind of thing within my scripts:
` "wdio-rerun-ios": "MOBILE_OS=IOS wdio run src/config/wdio.local.conf.ts && output/wdio-rerun-script.sh"`
then running `yarn run wdio-rerun-ios`

It, however, basically ignores the re-run script and the other way around it says it can't find the wdio config so that's a non-starter.
If anyone can point me in the right direction or to some useful documentation around this in general it would be greatly appreciated.

I realise this is not really an issue with the service but maybe an oversight in the docs/ or at least worthy of an example.

Thanks

**Comment by esaari** [comment]
@suleytron Thanks for opening an issue. Yes, this aspect could use some clarification. 

This is how I do it in my project: 
Assuming `rerun.sh` was generated, I have a secondary shell script that only initiates the rerun if its below a certain threshold of failures (no point in rerunning a suite that's almost completely bombed, something else would be afoot):

```
#!/usr/bin/env bash
MAX_TO_RERUN=${MAX_TO_RERUN:=250}
if [ -f "rerun.sh" ]; then
  echo "[rerun.sh] file exits, checking total failures."
  NUMBER_OF_FAILURES=$(grep "\-\-spec" -o rerun.sh | wc -l | xargs)
	if [ "$MAX_TO_RERUN" -gt "$NUMBER_OF_FAILURES" ]; then
    echo "Re-running $NUMBER_OF_FAILURES failed scenarios!"
    . ./rerun.sh
	else
    echo "Skipping re-run, expected < $MAX_TO_RERUN failures to qualify execution for re-run, got $NUMBER_OF_FAILURES failures."
	fi
else
  echo "No [rerun.sh] file exits, skipping re-run!"
fi
```

I then have an `attempt-rerun` script in my `package.json`: 
```
    "attempt-rerun": ". ./attemptRerun.sh"
```    
Which I then run in my actual execution script after the primary test run:
```
npm run "$CUCUMBER_PROFILE"
npm run attempt-rerun
```
There's certainly no hard and fast rule for how to do this, but I think we do need to make it obvious WDIO will not automatically rerun failed scenarios without any intervention.

**Comment by mikesalvia** [comment]
@suleytron and @esaari PR for documentation is up!
