### ISSUE TITLE
Rerunning individual Cucumber scenario reruns entire feature file

### ISSUE THREAD

**Issue by esaari** [webdriverio-community/wdio-rerun-service#65]
This is not a problem with the rerun service itself, but due to an upstream issue somewhere in the main WDIO codebase:

https://github.com/webdriverio/webdriverio/issues/7735

The `rerun.sh` file specifies a line number like so:  
```
rerun.sh
-----------
DISABLE_RERUN=true node_modules/.bin/wdio ./wdio-configs/local-chrome.conf.js   --spec=/Users/esaari/code/jwplayer-commercial/test/cucumber-features/basic/basic_mp4.feature:5
```

Due to the bug listed above, the entire feature file is being run which is causing unintended scenarios to be rerun. 

Leaving this issue open for visibility in case anybody running Cucumber is experiencing the same behavior. A fix was attempted by the original issue reporter, but abandoned: https://github.com/webdriverio/webdriverio/pull/7752

**Comment by mikesalvia** [comment]
Please post exact versions for 'webdriveri' dependencies.

**Comment by cesar-rivera** [comment]
I reproduced this issue with a basic project, here's the package.json
```
{
  "name": "my-new-project",
  "type": "module",
  "devDependencies": {
    "@wdio/allure-reporter": "^8.2.0",
    "@wdio/cli": "^8.2.4",
    "@wdio/cucumber-framework": "^8.2.3",
    "@wdio/junit-reporter": "^8.2.0",
    "@wdio/local-runner": "^8.2.4",
    "@wdio/spec-reporter": "^8.1.2",
    "chromedriver": "^109.0.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4",
    "wdio-chromedriver-service": "^8.0.1"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.conf.ts"
  }
}
```

here's the command I use
```
npm run wdio -- --spec="/Users/carc/projects/wdio-nextgen/features/login.feature:9"
```

and this is the repo for that project
https://github.com/cesar-rivera/wdio-basicproject

**Comment by mikesalvia** [comment]
@esaari @christian-bromann @cesar-rivera Found this issue occurs as of 7.20.6 last working version is 7.20.3, I am looking into what changed.

**Comment by Grubsniff** [comment]
Hi just wondering if there's been any update to this issue or other fixes that may address it at all?

We recently started trying to upgrade to v8 of wdio packages, from v7 and have found this issue ^ with executing cucumber scenario via line number.

**Comment by esaari** [comment]
Fixed in https://github.com/webdriverio/webdriverio/pull/10772
